version: '3'
services:
  api:
    image: docker.io/sawssan02/api:1.0
    ports:
      - "5000:5000"
    volumes:
      - /home/ubuntu/data:/data
  nginx:
    image: docker.io/sawssan02/nginx-server
    ports:
      - "80:80"
