version: "3.8"

services:
  website:
    image: php:apache
    environment:
      - USERNAME=root
      - PASSWORD=root
    volumes:
      - ./website:/var/www/html
    depends_on:
      - simple-api
    ports:
      - "80:80"
      
  simple-api:
    build: ./simple_api
    ports:
      - "5000:5000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
