version: '3.7'

services:
  backend:
    build:
      context: ./simple_api  # Dossier contenant le Dockerfile Flask
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data  # Montage du répertoire des données
    environment:
      - student_age_file_path=/data/student_age.json

  frontend:
    build:
      context: ./website # Dossier contenant le Dockerfile PHP
    environment:
    - USERNAME=root
    - PASSWORD=root
    ports:
      - "80:80"
    depends_on:
      - backend  # Attendre que le backend soit lancé
