# Utiliser l'image de base Nginx
FROM nginx:latest

# Copier la configuration ou les fichiers nécessaires
# Si tu veux ajouter ta propre configuration Nginx
COPY nginx.conf /etc/nginx/nginx.conf

# Exposer le port 80 pour Nginx
EXPOSE 80
